## Question 1:

### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x = np.array([30, 50])
y = np.array([20, 50])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[30 50]
[20 50]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


## Question 2:

### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [2]:
array=np.zeros(10)
print("array of 10 zeros:", array)
array=np.ones(10)
print("array of 10 ones:", array)
array=np.ones(10)*5
print("array of 10 fives:", array)

array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Question 3:

### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [3]:
x = np.array([[10,20,30],[20,30,40]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[10 20 30]
 [20 30 40]]
Sum of all elements:
150
Sum of each column:
[30 50 70]
Sum of each row:
[60 90]


## Question 4:

### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [4]:
print("Add:", np.add(10, 40))
print("Subtract:", np.subtract(10, 40))

print("Multiply:", np.multiply(10, 40))

print("Divide:", np.divide(10, 40))

Add: 50
Subtract: -30
Multiply: 400
Divide: 0.25


## Question 5:

### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [5]:
print("sin: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cos: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tan: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sin: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cos: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


## Question 6:

### Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [6]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


## Question 7:

### Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [7]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Select specific columns:")
print(df[['name', 'score']])

Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0
